package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAgentAduitLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentAduitLog extends BaseAgentAduitLog<AgentAduitLog> {
	public static final AgentAduitLog dao = new AgentAduitLog();
	public static final String table = "t_agent_aduit_log";
}
