package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAgentRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentRank extends BaseAgentRank<AgentRank> {
	public static final AgentRank dao = new AgentRank();
	public static final String table = "t_agent_rank";
}
