package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAgentCommission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AgentCommission extends BaseAgentCommission<AgentCommission> {
	public static final AgentCommission dao = new AgentCommission();
	public static final String table = "t_agent_commission";
}
