package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAuthUserConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthUserConfig extends BaseAuthUserConfig<AuthUserConfig> {
	
	public static final String table = "t_auth_user_config";
}
