package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAuthCert;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthCert extends BaseAuthCert<AuthCert> {
	public static final AuthCert dao = new AuthCert();
	public static final String table = "t_auth_cert";
}
