package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseAuthUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AuthUser extends BaseAuthUser<AuthUser> {
	public static final AuthUser dao = new AuthUser();
	public static final String table = "t_auth_user";
}
