package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseBuyerProd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyerProd extends BaseBuyerProd<BuyerProd> {
	
	public static final String table = "t_buyer_prod";
}
