package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseBuyerUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyerUser extends BaseBuyerUser<BuyerUser> {
	public static final BuyerUser dao = new BuyerUser();
	public static final String table = "t_buyer_user";
}
