package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseBuyerReceiver;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyerReceiver extends BaseBuyerReceiver<BuyerReceiver> {
	public static final BuyerReceiver dao = new BuyerReceiver();
	public static final String table = "t_buyer_receiver";
}
