package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseCashback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cashback extends BaseCashback<Cashback> {
	public static final Cashback dao = new Cashback();
	public static final String table = "t_cashback";
}
