package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseCompTicket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompTicket extends BaseCompTicket<CompTicket> {
	public static final CompTicket dao = new CompTicket();
	public static final String table = "t_comp_ticket";
}
