package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseDeliveryTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliveryTemplate extends BaseDeliveryTemplate<DeliveryTemplate> {
	public static final DeliveryTemplate dao = new DeliveryTemplate();
	public static final String table = "t_delivery_template";
}
