package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseDeliverySet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeliverySet extends BaseDeliverySet<DeliverySet> {
	public static final DeliverySet dao = new DeliverySet();
	public static final String table = "t_delivery_set";
}
