package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseFullCutProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FullCutProduct extends BaseFullCutProduct<FullCutProduct> {
	public static final FullCutProduct dao = new FullCutProduct();
	public static final String table = "t_full_cut_product";
}
