package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseFullCutSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FullCutSet extends BaseFullCutSet<FullCutSet> {
	public static final FullCutSet dao = new FullCutSet();
	public static final String table = "t_full_cut_set";
}
