package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseLotteryRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryRecord extends BaseLotteryRecord<LotteryRecord> {
	public static final LotteryRecord dao = new LotteryRecord();
	public static final String table = "t_lottery_record";
}
