package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseLotteryTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryTrade extends BaseLotteryTrade<LotteryTrade> {
	public static final LotteryTrade dao = new LotteryTrade();
	public static final String table = "t_lottery_trade";
}
