package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseLotteryAward;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LotteryAward extends BaseLotteryAward<LotteryAward> {
	public static final LotteryAward dao = new LotteryAward();
	public static final String table = "t_lottery_award";
}
