package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseLottery;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lottery extends BaseLottery<Lottery> {
	public static final Lottery dao = new Lottery();
	public static final String table = "t_lottery";
}
