package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseMemberRank;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemberRank extends BaseMemberRank<MemberRank> {
	public static final String table = "t_member_rank";
}
