package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseModuleFun;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ModuleFun extends BaseModuleFun<ModuleFun> {
	public static final ModuleFun dao = new ModuleFun();
	public static final String table = "t_module_fun";
}
