package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseModule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Module extends BaseModule<Module> {
	public static final Module dao = new Module();
	public static final String table = "t_module";
}
