package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseOrderPressRcd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderPressRcd extends BaseOrderPressRcd<OrderPressRcd> {
	public static final String table = "t_order_press_rcd";
}
