package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseOrderGheader;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderGheader extends BaseOrderGheader<OrderGheader> {
	public static final String table = "t_order_gheader";
}
