package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseOrderGuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderGuser extends BaseOrderGuser<OrderGuser> {
	public static final String table = "t_order_guser";
}
