package com.dbumama.market.model;

import com.dbumama.market.model.base.BasePrizeType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrizeType extends BasePrizeType<PrizeType> {
	public static final PrizeType dao = new PrizeType();
	public static final String table = "t_prize_type";
}
