package com.dbumama.market.model;

import com.dbumama.market.model.base.BasePrize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Prize extends BasePrize<Prize> {
	public static final Prize dao = new Prize();
	public static final String table = "t_prize";
}
