package com.dbumama.market.model;

import com.dbumama.market.model.base.BasePrizeSendRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PrizeSendRecord extends BasePrizeSendRecord<PrizeSendRecord> {
	public static final PrizeSendRecord dao = new PrizeSendRecord();
	public static final String table = "t_prize_send_record";
}
