package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpecification extends BaseProductSpecification<ProductSpecification> {
	public static final ProductSpecification dao = new ProductSpecification();
	public static final String table = "t_product_specification";
}
