package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductSpecificationValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpecificationValue extends BaseProductSpecificationValue<ProductSpecificationValue> {
	public static final String table = "t_product_specification_value";
}
