package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductImage extends BaseProductImage<ProductImage> {
	public static final String table = "t_product_image";
}
