package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductBrand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductBrand extends BaseProductBrand<ProductBrand> {
	public static final String table = "t_product_brand";
}
