package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductCategory extends BaseProductCategory<ProductCategory> {
	public static final String table = "t_product_category";
}
