package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductSpecItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpecItem extends BaseProductSpecItem<ProductSpecItem> {
	public static final ProductSpecItem dao = new ProductSpecItem();
	public static final String table = "t_product_spec_item";
}
