package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product();
	public static final String table = "t_product";
	/**库存 *//*
	private List<ProductStock> stocks=new ArrayList<ProductStock>();
	*//** 商品图片 *//*
	private List<ProductImage> productImages = new ArrayList<ProductImage>();
	

	*//** page speci **//*
	private List<Specification> specifications4Page = new ArrayList<Specification>();
	
	*//** 规格值 *//*
	private List<SpecificationValue> specificationValues4Page = new ArrayList<SpecificationValue>();
	
	
	public List<ProductStock> getStocks() {
		return stocks;
	}

	public void setStocks(List<ProductStock> stocks) {
		this.stocks = stocks;
	}

	public List<ProductImage> getProductImages() {
		return productImages;
	}

	public void setProductImages(List<ProductImage> productImages) {
		this.productImages = productImages;
	}

	public List<Specification> getSpecifications4Page() {
		return specifications4Page;
	}

	public void setSpecifications4Page(List<Specification> specifications4Page) {
		this.specifications4Page = specifications4Page;
	}

	public List<SpecificationValue> getSpecificationValues4Page() {
		return specificationValues4Page;
	}
	
	
	public void setSpecificationValues4Page(List<SpecificationValue> specificationValues4Page) {
		this.specificationValues4Page = specificationValues4Page;
	}*/

	
}
