package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final String table = "t_product";
}
