package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductImage;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductImage extends BaseProductImage<ProductImage> {
	public static final ProductImage dao = new ProductImage();
	public static final String table = "t_product_image";
}
