package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductGroup extends BaseProductGroup<ProductGroup> {
	public static final String table = "t_product_group";
}
