package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductSpecificationValue;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductSpecificationValue extends BaseProductSpecificationValue<ProductSpecificationValue> {
	public static final ProductSpecificationValue dao = new ProductSpecificationValue();
	public static final String table = "t_product_specification_value";
}
