package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseProductGroupSet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductGroupSet extends BaseProductGroupSet<ProductGroupSet> {
	public static final String table = "t_product_group_set";
}
