package com.dbumama.market.model;

import com.dbumama.market.model.base.BasePromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Promotion extends BasePromotion<Promotion> {
	public static final Promotion dao = new Promotion();
	public static final String table = "t_promotion";
}
