package com.dbumama.market.model;

import com.dbumama.market.model.base.BasePurchase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Purchase extends BasePurchase<Purchase> {
	public static final Purchase dao = new Purchase();
	public static final String table = "t_purchase";
}
