package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseQiandaoRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QiandaoRecord extends BaseQiandaoRecord<QiandaoRecord> {
	public static final QiandaoRecord dao = new QiandaoRecord();
	public static final String table = "t_qiandao_record";
}
