package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseQiandaoUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QiandaoUser extends BaseQiandaoUser<QiandaoUser> {
	public static final QiandaoUser dao = new QiandaoUser();
	public static final String table = "t_qiandao_user";
}
