package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseSellerImages;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SellerImages extends BaseSellerImages<SellerImages> {
	public static final SellerImages dao = new SellerImages();
	public static final String table = "t_seller_images";
}
