package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseSellerUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SellerUser extends BaseSellerUser<SellerUser> {
	public static final SellerUser dao = new SellerUser();
	public static final String table = "t_seller_user";
}
