package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseSellerAddr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SellerAddr extends BaseSellerAddr<SellerAddr> {
	public static final SellerAddr dao = new SellerAddr();
	public static final String table = "t_seller_addr";
}
