package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Specification extends BaseSpecification<Specification> {
	public static final Specification dao = new Specification();
	public static final String table = "t_specification";
	//String sql = "SELECT * FROM t_product_specification ps INNER JOIN t_product p ON ps.products = p.id WHERE ps.specifications = ?";

	
}
