package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseSpecificationValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecificationValue extends BaseSpecificationValue<SpecificationValue> {
	public static final String table = "t_specification_value";
}
