package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseSpecification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Specification extends BaseSpecification<Specification> {
	public static final String table = "t_specification";
}
