package com.dbumama.market.model;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.collections4.CollectionUtils;

import com.dbumama.market.model.base.BaseSpecificationValue;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SpecificationValue extends BaseSpecificationValue<SpecificationValue> {
	public static final SpecificationValue dao = new SpecificationValue();
	public static final String table = "t_specification_value";
	
	/** 商品 */
	private List<Product> products = new ArrayList<Product>();
	

	/**
	 * 根据specificationId删除参数
	 * @param specificationId
	 * @return
	 */
	public boolean delete(Long specificationId) {
		return Db.deleteById(table, "specification_id", specificationId);
	}
	
	/**
	 * 获取规格
	 * 
	 * @return 规格
	 */
	public Specification getSpecification() {
		return Specification.dao.findById(getSpecificationId());
	}
	
	/**
	 * 获取商品
	 * 
	 * @return 商品
	 */
	public List<Product> getProducts() {
		String sql = "SELECT p.* FROM `t_product_specification_value` psv INNER JOIN `t_product` p ON psv.`products` = p.`id` WHERE psv.`specification_values` = ?";
		if (CollectionUtils.isEmpty(products)) {
			products = Product.dao.find(sql, getId());
		}
		return products;
	}

	/**
	 * 设置商品
	 * 
	 * @param products
	 *            商品
	 */
	public void setProducts(List<Product> products) {
		this.products = products;
	}
}
