package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseUserCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserCode extends BaseUserCode<UserCode> {
	public static final UserCode dao = new UserCode();
	public static final String table = "t_user_code";
}
