package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseWeapp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Weapp extends BaseWeapp<Weapp> {
	
	public static final String table = "t_weapp";
}
