package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseWeappAudit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeappAudit extends BaseWeappAudit<WeappAudit> {
	public static final String table = "t_weapp_audit";
}
