package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseWeipageCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeipageCategory extends BaseWeipageCategory<WeipageCategory> {
	public static final String table = "t_weipage_category";
}
