package com.dbumama.market.model;

import com.dbumama.market.model.base.BaseWeiPage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeiPage extends BaseWeiPage<WeiPage> {
	public static final String table = "t_wei_page";
}
