spring:
  application:
    name: fastcms
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cache:
    type: ehcache
  freemarker:
    checkTemplateLocation: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fastcms?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/*Mapper.xml

plugin:
  path: ./plugins

fastcms:
  auth:
    token:
      expire:
        seconds: 18000
      secret-key: SecretKey012345678901234567890123456789012345678901234567890123456789
  security:
    ignore:
      urls: "/fastcms/api/admin/login,\
      /fastcms/api/admin/register,\
      /fastcms/api/admin/reset/password,\
      /fastcms/api/admin/config/public/list,\
      /fastcms/api/admin/captcha,\
      /fastcms/api/client/wechat/miniapp/user/code2session,\
      /fastcms/api/client/wechat/miniapp/user/login,\
      /fastcms/api/client/wechat/miniapp/user/login/phone"
  config:
    ignore:
      keys: "wechat_mch_secret"
  mybatis:
    ignore:
      mappedStatementIds: "selectById, selectBatchIds, getArticleById"

logging:
  config: classpath:META-INF/logback/fastcms.xml

server:
  servlet:
    encoding:
      force: true
