server:
  servlet:
    context-path: /fastcms

spring:
  application:
    name: fastcms
  profiles:
    active: dev
  cache:
    type: ehcache
  freemarker:
    checkTemplateLocation: false


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fastcms?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:/mapper/*Mapper.xml

plugin:
  path: ./plugins

jwt:
  secret: xjd2020
md5:
  sign:
    key: fastcms2021


