CREATE TABLE `article_zan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `create_user_id` bigint(20) DEFAULT NULL,
  `article_id` bigint(20) DEFAULT NULL,
  `created` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;

ALTER TABLE `article` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';
ALTER TABLE `article_category` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';
ALTER TABLE `article_comment` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';
ALTER TABLE `article_tag` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';
ALTER TABLE `single_page` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';
ALTER TABLE `single_page_comment` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';
ALTER TABLE `menu` ADD COLUMN `language` varchar(64) DEFAULT NULL COMMENT '语言';

delete from `permission`;
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('1', '0', 'home', '/home', 'home/index', 'message.router.home', 'iconfont icon-shouye', '0', '0', '1', '1', '0', '0', 'admin', '2021-10-31 23:48:10', '2022-02-19 13:30:50');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('2', '0', 'system', '/system', 'layout/routerView/parent', 'message.router.system', 'ele-Lollipop', '0', '0', '0', '0', '0', '0', 'admin', '2021-11-07 18:16:47', '2023-05-16 00:15:02');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('3', '2', 'systemMenu', '/system/menu', 'system/menu/index', 'message.router.systemMenu', 'iconfont icon-caidan', '0', '0', '0', '0', '0', '0', 'admin', '2021-11-07 18:18:00', NULL);
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('4', '2', 'systemRole', '/system/role', 'system/role/index', 'message.router.systemRole', 'ele-Avatar', '0', '0', '0', '0', '0', '0', 'admin', '2021-11-08 12:00:50', '2023-05-14 23:19:31');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('5', '2', 'systemUser', '/system/user', 'system/user/index', 'message.router.systemUser', 'ele-User', '0', '0', '0', '0', '0', '3', 'admin', '2021-11-08 12:02:28', '2023-05-16 00:03:53');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('6', '0', 'attach', '/attach', 'layout/routerView/parent', 'message.router.attach', 'ele-Folder', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:05:27', '2023-05-16 00:09:54');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('7', '6', 'attachManager', '/attach/index', 'attach/index', 'message.router.attachManager', 'ele-CopyDocument', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:11:16', '2023-05-16 00:09:01');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('8', '6', 'attachSet', '/attach/set', 'attach/set', 'message.router.attachSet', 'iconfont icon-quanjushezhi_o', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:12:33', '2023-05-16 00:13:44');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('9', '0', 'plugin', '/plugin', 'layout/routerView/parent', 'message.router.plugin', 'ele-Management', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:14:05', '2023-05-16 00:12:32');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('10', '9', 'pluginManager', '/plugin/index', 'plugin/index', 'message.router.pluginManager', 'ele-Connection', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:15:58', '2023-05-28 21:14:57');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('11', '0', 'article', '/article', 'layout/routerView/parent', 'message.router.article', 'ele-Document', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:18:10', '2023-05-28 21:15:14');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('12', '11', 'articleManager', '/article/index', 'article/index', 'message.router.articleManager', 'ele-DocumentCopy', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:18:50', '2023-05-28 21:15:41');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('13', '11', 'articleWrite', '/article/write', 'article/write', 'message.router.articleWrite', 'ele-DocumentAdd', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:18:50', '2023-05-28 21:15:54');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('14', '11', 'articleCategory', '/article/category', 'article/category', 'message.router.articleCategory', 'iconfont icon-juxingkaobei', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:20:16', '2023-05-28 21:16:15');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('15', '11', 'articleComment', '/article/comment', 'article/comment', 'message.router.articleComment', 'ele-Comment', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:21:14', '2023-05-28 21:16:32');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('16', '11', 'articleSet', '/article/set', 'article/set', 'message.router.articleSet', 'iconfont icon-quanjushezhi_o', '0', '0', '0', '0', '0', '990', '', '2021-11-21 10:19:39', '2023-05-28 21:17:51');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('17', '0', 'page', '/page', 'layout/routerView/parent', 'message.router.page', 'ele-DocumentCopy', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:22:10', '2023-05-28 21:18:49');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('18', '17', 'pageManager', '/page/index', 'page/index', 'message.router.pageManager', 'ele-Tickets', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:23:22', '2023-05-28 21:19:26');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('19', '17', 'pageWrite', '/page/write', 'page/write', 'message.router.pageWrite', 'ele-Edit', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:25:56', '2023-05-28 21:19:57');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('20', '17', 'pageComment', '/page/comment', 'page/comment', 'message.router.pageComment', 'ele-Comment', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:25:56', '2023-05-28 21:21:01');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('21', '17', 'pageSet', '/page/set', 'page/set', 'message.router.pageSet', 'ele-Setting', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:26:27', '2023-05-28 21:21:25');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('22', '0', 'template', '/template', 'layout/routerView/parent', 'message.router.template', 'ele-FolderOpened', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:28:05', '2023-05-28 21:24:26');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('23', '22', 'templateManager', '/template/index', 'template/index', 'message.router.templateManager', 'ele-Folder', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:28:39', '2023-05-28 21:25:38');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('24', '22', 'templateEdit', '/template/edit', 'template/edit', 'message.router.templateEdit', 'ele-EditPen', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:29:13', '2023-05-28 21:26:05');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('25', '22', 'templateMenu', '/template/menu', 'template/menu', 'message.router.templateMenu', 'ele-Memo', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:29:49', '2023-05-28 21:26:43');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('26', '22', 'templateSet', '/template/set', 'template/set', 'message.router.templateSet', 'ele-Setting', '0', '0', '0', '0', '0', '0', '', '2021-11-21 10:30:17', '2023-05-28 21:26:58');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('27', '0', 'setting', '/setting', 'layout/routerView/parent', 'message.router.setting', 'iconfont icon-quanjushezhi_o', '0', '0', '0', '0', '0', '999', '', '2021-12-02 14:28:36', '2023-05-16 00:14:06');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('28', '27', 'websiteSet', '/setting/website', 'setting/website', 'message.router.websiteSet', 'ele-Eleme', '0', '0', '0', '0', '0', '0', '', '2021-12-02 14:30:44', '2023-05-28 21:33:01');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('29', '0', 'order', '/order', 'layout/routerView/parent', 'message.router.order', 'ele-ShoppingCart', '0', '0', '0', '0', '0', '0', '', '2022-02-19 11:30:56', '2023-05-28 21:29:13');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('30', '29', 'orderManager', '/order/index', 'order/index', 'message.router.orderManager', 'ele-ShoppingTrolley', '0', '0', '0', '0', '0', '0', '', '2022-02-19 11:33:21', '2023-05-28 21:29:34');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('31', '29', 'orderSet', '/order/set', 'order/set', 'message.router.orderSet', 'ele-Setting', '0', '0', '0', '0', '0', '999', '', '2022-02-19 11:34:19', '2023-05-28 21:31:10');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('32', '27', 'wechatSet', '/setting/wechat', 'setting/wechat', 'message.router.wechatSet', 'ele-ChatRound', '0', '0', '0', '0', '0', '0', '', '2022-03-02 23:18:57', '2023-05-28 21:33:18');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('33', '27', 'connectionSet', '/setting/connection', 'setting/connection', 'message.router.connectionSet', 'ele-Phone', '0', '0', '0', '0', '0', '0', '', '2022-03-22 20:22:34', '2023-05-28 21:33:41');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('34', '2', 'systemDept', '/system/dept', 'system/dept/index', 'message.router.systemDept', 'iconfont icon-shuxingtu', '0', '0', '0', '0', '0', '0', '', '2022-03-23 19:35:15', '2023-05-16 00:04:23');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('35', '29', 'paymentManager', '/payment/index', 'payment/index', 'message.router.paymentManager', 'ele-ScaleToOriginal', '0', '0', '0', '0', '0', '0', '', '2022-04-07 11:22:16', '2023-05-28 21:29:55');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('36', '29', 'cashoutManager', '/cashout/index', 'cashout/index', 'message.router.cashoutManager', 'ele-Finished', '0', '0', '0', '0', '0', '0', '', '2022-04-07 11:25:14', '2023-05-28 21:30:50');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('37', '0', 'user', '/user', 'layout/routerView/parent', 'message.router.user', 'ele-Avatar', '0', '0', '0', '0', '0', '0', '', '2022-04-27 11:02:31', '2023-05-28 21:31:34');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('38', '37', 'userManager', '/user/index', 'user/index', 'message.router.userManager', 'ele-User', '0', '0', '0', '0', '0', '0', '', '2022-04-27 11:13:00', '2023-05-28 21:31:55');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('39', '2', 'systemRes', '/system/res', 'system/res/index', 'message.router.systemRes', 'iconfont icon-zidingyibuju', '0', '0', '0', '0', '0', '0', '', '2022-05-02 18:15:51', '2023-05-16 00:07:32');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('40', '27', 'systemSet', '/setting/system', 'setting/system', 'message.router.systemSet', 'ele-Promotion', '0', '0', '0', '0', '0', '0', '', '2022-08-06 12:48:45', '2023-05-28 21:34:38');
INSERT INTO `permission` (`id`, `parent_id`, `name`, `path`, `component`, `title`, `icon`, `is_link`, `is_hide`, `is_keep_alive`, `is_affix`, `is_iframe`, `sort_num`, `category`, `created`, `updated`) VALUES ('41', '11', 'articleTag', '/article/tag', 'article/tag', 'message.router.articleTag', 'ele-PriceTag', '0', '0', '0', '0', '0', '0', '', '2022-11-25 16:05:46', '2023-05-28 21:16:59');
