package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAuthUserConfig<M extends BaseAuthUserConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setAppName(java.lang.String appName) {
		set("app_name", appName);
		return (M)this;
	}

	public java.lang.String getAppName() {
		return get("app_name");
	}

	public M setAppId(java.lang.String appId) {
		set("app_id", appId);
		return (M)this;
	}

	public java.lang.String getAppId() {
		return get("app_id");
	}

	public M setAppSecret(java.lang.String appSecret) {
		set("app_secret", appSecret);
		return (M)this;
	}

	public java.lang.String getAppSecret() {
		return get("app_secret");
	}

	public M setAdminDomain(java.lang.String adminDomain) {
		set("admin_domain", adminDomain);
		return (M)this;
	}

	public java.lang.String getAdminDomain() {
		return get("admin_domain");
	}

	public M setWxDomain(java.lang.String wxDomain) {
		set("wx_domain", wxDomain);
		return (M)this;
	}

	public java.lang.String getWxDomain() {
		return get("wx_domain");
	}

	public M setImgDomain(java.lang.String imgDomain) {
		set("img_domain", imgDomain);
		return (M)this;
	}

	public java.lang.String getImgDomain() {
		return get("img_domain");
	}

	public M setMsgServerUrl(java.lang.String msgServerUrl) {
		set("msg_server_url", msgServerUrl);
		return (M)this;
	}

	public java.lang.String getMsgServerUrl() {
		return get("msg_server_url");
	}

	public M setMsgToken(java.lang.String msgToken) {
		set("msg_token", msgToken);
		return (M)this;
	}

	public java.lang.String getMsgToken() {
		return get("msg_token");
	}

	public M setMsgAesKey(java.lang.String msgAesKey) {
		set("msg_aes_key", msgAesKey);
		return (M)this;
	}

	public java.lang.String getMsgAesKey() {
		return get("msg_aes_key");
	}

	public M setPayMchId(java.lang.String payMchId) {
		set("pay_mch_id", payMchId);
		return (M)this;
	}

	public java.lang.String getPayMchId() {
		return get("pay_mch_id");
	}

	public M setPaySecretKey(java.lang.String paySecretKey) {
		set("pay_secret_key", paySecretKey);
		return (M)this;
	}

	public java.lang.String getPaySecretKey() {
		return get("pay_secret_key");
	}

	public M setPayCertFile(byte[] payCertFile) {
		set("pay_cert_file", payCertFile);
		return (M)this;
	}

	public byte[] getPayCertFile() {
		return get("pay_cert_file");
	}

	public M setPayResultUrl(java.lang.String payResultUrl) {
		set("pay_result_url", payResultUrl);
		return (M)this;
	}

	public java.lang.String getPayResultUrl() {
		return get("pay_result_url");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
