package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExpressTemplate<M extends BaseExpressTemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setExpName(java.lang.String expName) {
		set("exp_name", expName);
	}

	public java.lang.String getExpName() {
		return get("exp_name");
	}

	public void setExpKey(java.lang.String expKey) {
		set("exp_key", expKey);
	}

	public java.lang.String getExpKey() {
		return get("exp_key");
	}

	public void setExpTplcontent(java.lang.String expTplcontent) {
		set("exp_tplcontent", expTplcontent);
	}

	public java.lang.String getExpTplcontent() {
		return get("exp_tplcontent");
	}

	public void setExpDesignhtml(java.lang.String expDesignhtml) {
		set("exp_designhtml", expDesignhtml);
	}

	public java.lang.String getExpDesignhtml() {
		return get("exp_designhtml");
	}

	public void setExpBgimg(java.lang.String expBgimg) {
		set("exp_bgimg", expBgimg);
	}

	public java.lang.String getExpBgimg() {
		return get("exp_bgimg");
	}

	public void setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
	}

	public java.lang.Integer getIsDefault() {
		return get("is_default");
	}

	public void setPagewidth(java.lang.Integer pagewidth) {
		set("pagewidth", pagewidth);
	}

	public java.lang.Integer getPagewidth() {
		return get("pagewidth");
	}

	public void setPageheight(java.lang.Integer pageheight) {
		set("pageheight", pageheight);
	}

	public java.lang.Integer getPageheight() {
		return get("pageheight");
	}

	public void setOffsetx(java.lang.Integer offsetx) {
		set("offsetx", offsetx);
	}

	public java.lang.Integer getOffsetx() {
		return get("offsetx");
	}

	public void setOffsety(java.lang.Integer offsety) {
		set("offsety", offsety);
	}

	public java.lang.Integer getOffsety() {
		return get("offsety");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
