package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExpressComp<M extends BaseExpressComp<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setExpKey(java.lang.String expKey) {
		set("exp_key", expKey);
	}

	public java.lang.String getExpKey() {
		return get("exp_key");
	}

	public void setCompanyCode(java.lang.String companyCode) {
		set("company_code", companyCode);
	}

	public java.lang.String getCompanyCode() {
		return get("company_code");
	}

	public void setExpName(java.lang.String expName) {
		set("exp_name", expName);
	}

	public java.lang.String getExpName() {
		return get("exp_name");
	}

}
