package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLottery<M extends BaseLottery<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setLotteryName(java.lang.String lotteryName) {
		set("lottery_name", lotteryName);
	}

	public java.lang.String getLotteryName() {
		return get("lottery_name");
	}

	public void setLotteryType(java.lang.Integer lotteryType) {
		set("lottery_type", lotteryType);
	}

	public java.lang.Integer getLotteryType() {
		return get("lottery_type");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setActivityType(java.lang.Integer activityType) {
		set("activity_type", activityType);
	}

	public java.lang.Integer getActivityType() {
		return get("activity_type");
	}

	public void setAllCount(java.lang.Integer allCount) {
		set("all_count", allCount);
	}

	public java.lang.Integer getAllCount() {
		return get("all_count");
	}

	public void setDayCount(java.lang.Integer dayCount) {
		set("day_count", dayCount);
	}

	public java.lang.Integer getDayCount() {
		return get("day_count");
	}

	public void setLuckCount(java.lang.Integer luckCount) {
		set("luck_count", luckCount);
	}

	public java.lang.Integer getLuckCount() {
		return get("luck_count");
	}

	public void setConditionType(java.lang.Integer conditionType) {
		set("condition_type", conditionType);
	}

	public java.lang.Integer getConditionType() {
		return get("condition_type");
	}

	public void setLotteryMemo(java.lang.String lotteryMemo) {
		set("lottery_memo", lotteryMemo);
	}

	public java.lang.String getLotteryMemo() {
		return get("lottery_memo");
	}

	public void setNeedCollectShop(java.lang.Integer needCollectShop) {
		set("need_collect_shop", needCollectShop);
	}

	public java.lang.Integer getNeedCollectShop() {
		return get("need_collect_shop");
	}

	public void setNeedPay(java.lang.Integer needPay) {
		set("need_pay", needPay);
	}

	public java.lang.Integer getNeedPay() {
		return get("need_pay");
	}

	public void setWirlessUrl(java.lang.String wirlessUrl) {
		set("wirless_url", wirlessUrl);
	}

	public java.lang.String getWirlessUrl() {
		return get("wirless_url");
	}

	public void setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
	}

	public java.lang.String getQrCode() {
		return get("qr_code");
	}

	public void setBackImg(java.lang.String backImg) {
		set("back_img", backImg);
	}

	public java.lang.String getBackImg() {
		return get("back_img");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
