package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLottery<M extends BaseLottery<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setLotteryName(java.lang.String lotteryName) {
		set("lottery_name", lotteryName);
		return (M)this;
	}

	public java.lang.String getLotteryName() {
		return get("lottery_name");
	}

	public M setLotteryType(java.lang.Integer lotteryType) {
		set("lottery_type", lotteryType);
		return (M)this;
	}

	public java.lang.Integer getLotteryType() {
		return get("lottery_type");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setActivityType(java.lang.Integer activityType) {
		set("activity_type", activityType);
		return (M)this;
	}

	public java.lang.Integer getActivityType() {
		return get("activity_type");
	}

	public M setAllCount(java.lang.Integer allCount) {
		set("all_count", allCount);
		return (M)this;
	}

	public java.lang.Integer getAllCount() {
		return get("all_count");
	}

	public M setDayCount(java.lang.Integer dayCount) {
		set("day_count", dayCount);
		return (M)this;
	}

	public java.lang.Integer getDayCount() {
		return get("day_count");
	}

	public M setLuckCount(java.lang.Integer luckCount) {
		set("luck_count", luckCount);
		return (M)this;
	}

	public java.lang.Integer getLuckCount() {
		return get("luck_count");
	}

	public M setConditionType(java.lang.Integer conditionType) {
		set("condition_type", conditionType);
		return (M)this;
	}

	public java.lang.Integer getConditionType() {
		return get("condition_type");
	}

	public M setLotteryMemo(java.lang.String lotteryMemo) {
		set("lottery_memo", lotteryMemo);
		return (M)this;
	}

	public java.lang.String getLotteryMemo() {
		return get("lottery_memo");
	}

	public M setNeedCollectShop(java.lang.Integer needCollectShop) {
		set("need_collect_shop", needCollectShop);
		return (M)this;
	}

	public java.lang.Integer getNeedCollectShop() {
		return get("need_collect_shop");
	}

	public M setNeedPay(java.lang.Integer needPay) {
		set("need_pay", needPay);
		return (M)this;
	}

	public java.lang.Integer getNeedPay() {
		return get("need_pay");
	}

	public M setWirlessUrl(java.lang.String wirlessUrl) {
		set("wirless_url", wirlessUrl);
		return (M)this;
	}

	public java.lang.String getWirlessUrl() {
		return get("wirless_url");
	}

	public M setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
		return (M)this;
	}

	public java.lang.String getQrCode() {
		return get("qr_code");
	}

	public M setBackImg(java.lang.String backImg) {
		set("back_img", backImg);
		return (M)this;
	}

	public java.lang.String getBackImg() {
		return get("back_img");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
