package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePurchaseOrder<M extends BasePurchaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public void setPurchaseId(java.lang.Long purchaseId) {
		set("purchase_id", purchaseId);
	}

	public java.lang.Long getPurchaseId() {
		return get("purchase_id");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public void setAlipayTradeNo(java.lang.String alipayTradeNo) {
		set("alipay_trade_no", alipayTradeNo);
	}

	public java.lang.String getAlipayTradeNo() {
		return get("alipay_trade_no");
	}

	public void setPayFee(java.lang.Double payFee) {
		set("pay_fee", payFee);
	}

	public java.lang.Double getPayFee() {
		return get("pay_fee");
	}

	public void setPayType(java.lang.String payType) {
		set("pay_type", payType);
	}

	public java.lang.String getPayType() {
		return get("pay_type");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
