package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePromotionSet<M extends BasePromotionSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setPromotionId(java.lang.Long promotionId) {
		set("promotion_id", promotionId);
	}

	public java.lang.Long getPromotionId() {
		return get("promotion_id");
	}

	public void setProductId(java.lang.Long productId) {
		set("product_id", productId);
	}

	public java.lang.Long getProductId() {
		return get("product_id");
	}

	public void setPromotionType(java.lang.Integer promotionType) {
		set("promotion_type", promotionType);
	}

	public java.lang.Integer getPromotionType() {
		return get("promotion_type");
	}

	public void setPromotionSetZhekou(java.lang.Float promotionSetZhekou) {
		set("promotion_set_zhekou", promotionSetZhekou);
	}

	public java.lang.Float getPromotionSetZhekou() {
		return get("promotion_set_zhekou");
	}

	public void setPromotionSetJianjia(java.lang.Float promotionSetJianjia) {
		set("promotion_set_jianjia", promotionSetJianjia);
	}

	public java.lang.Float getPromotionSetJianjia() {
		return get("promotion_set_jianjia");
	}

	public void setPromotionValue(java.lang.Float promotionValue) {
		set("promotion_value", promotionValue);
	}

	public java.lang.Float getPromotionValue() {
		return get("promotion_value");
	}

	public void setActive(java.lang.Boolean active) {
		set("active", active);
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
