package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQiandaoUser<M extends BaseQiandaoUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setQiandaoId(java.lang.Long qiandaoId) {
		set("qiandao_id", qiandaoId);
		return (M)this;
	}

	public java.lang.Long getQiandaoId() {
		return get("qiandao_id");
	}

	public M setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public M setQiandaoCount(java.lang.Integer qiandaoCount) {
		set("qiandao_count", qiandaoCount);
		return (M)this;
	}

	public java.lang.Integer getQiandaoCount() {
		return get("qiandao_count");
	}

	public M setCQiandaoCount(java.lang.Integer cQiandaoCount) {
		set("c_qiandao_count", cQiandaoCount);
		return (M)this;
	}

	public java.lang.Integer getCQiandaoCount() {
		return get("c_qiandao_count");
	}

	public M setSignDate(java.util.Date signDate) {
		set("sign_date", signDate);
		return (M)this;
	}

	public java.util.Date getSignDate() {
		return get("sign_date");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
