package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMemberRank<M extends BaseMemberRank<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setRankName(java.lang.String rankName) {
		set("rank_name", rankName);
		return (M)this;
	}

	public java.lang.String getRankName() {
		return get("rank_name");
	}

	public M setFirstCharge(java.math.BigDecimal firstCharge) {
		set("first_charge", firstCharge);
		return (M)this;
	}

	public java.math.BigDecimal getFirstCharge() {
		return get("first_charge");
	}

	public M setRankDiscount(java.math.BigDecimal rankDiscount) {
		set("rank_discount", rankDiscount);
		return (M)this;
	}

	public java.math.BigDecimal getRankDiscount() {
		return get("rank_discount");
	}

	public M setRankCashFull(java.math.BigDecimal rankCashFull) {
		set("rank_cash_full", rankCashFull);
		return (M)this;
	}

	public java.math.BigDecimal getRankCashFull() {
		return get("rank_cash_full");
	}

	public M setRankCashRward(java.math.BigDecimal rankCashRward) {
		set("rank_cash_rward", rankCashRward);
		return (M)this;
	}

	public java.math.BigDecimal getRankCashRward() {
		return get("rank_cash_rward");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
