package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePurchaseOrder<M extends BasePurchaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}

	public java.lang.Long getUserId() {
		return get("user_id");
	}

	public M setPurchaseId(java.lang.Long purchaseId) {
		set("purchase_id", purchaseId);
		return (M)this;
	}

	public java.lang.Long getPurchaseId() {
		return get("purchase_id");
	}

	public M setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
		return (M)this;
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public M setAlipayTradeNo(java.lang.String alipayTradeNo) {
		set("alipay_trade_no", alipayTradeNo);
		return (M)this;
	}

	public java.lang.String getAlipayTradeNo() {
		return get("alipay_trade_no");
	}

	public M setPayFee(java.lang.Double payFee) {
		set("pay_fee", payFee);
		return (M)this;
	}

	public java.lang.Double getPayFee() {
		return get("pay_fee");
	}

	public M setPayType(java.lang.String payType) {
		set("pay_type", payType);
		return (M)this;
	}

	public java.lang.String getPayType() {
		return get("pay_type");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
