package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductSpecificationValue<M extends BaseProductSpecificationValue<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setProductId(java.lang.Long productId) {
		set("product_id", productId);
		return (M)this;
	}

	public java.lang.Long getProductId() {
		return get("product_id");
	}

	public M setSpecificationId(java.lang.Long specificationId) {
		set("specification_id", specificationId);
		return (M)this;
	}

	public java.lang.Long getSpecificationId() {
		return get("specification_id");
	}

	public M setSpecificationValueId(java.lang.Long specificationValueId) {
		set("specification_value_id", specificationValueId);
		return (M)this;
	}

	public java.lang.Long getSpecificationValueId() {
		return get("specification_value_id");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
