package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQiandao<M extends BaseQiandao<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setQiandaoName(java.lang.String qiandaoName) {
		set("qiandao_name", qiandaoName);
		return (M)this;
	}

	public java.lang.String getQiandaoName() {
		return get("qiandao_name");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setActivityType(java.lang.Integer activityType) {
		set("activity_type", activityType);
		return (M)this;
	}

	public java.lang.Integer getActivityType() {
		return get("activity_type");
	}

	public M setQiandaoMemo(java.lang.String qiandaoMemo) {
		set("qiandao_memo", qiandaoMemo);
		return (M)this;
	}

	public java.lang.String getQiandaoMemo() {
		return get("qiandao_memo");
	}

	public M setWirlessUrl(java.lang.String wirlessUrl) {
		set("wirless_url", wirlessUrl);
		return (M)this;
	}

	public java.lang.String getWirlessUrl() {
		return get("wirless_url");
	}

	public M setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
		return (M)this;
	}

	public java.lang.String getQrCode() {
		return get("qr_code");
	}

	public M setBackImg(java.lang.String backImg) {
		set("back_img", backImg);
		return (M)this;
	}

	public java.lang.String getBackImg() {
		return get("back_img");
	}

	public M setNeedCollectShop(java.lang.Integer needCollectShop) {
		set("need_collect_shop", needCollectShop);
		return (M)this;
	}

	public java.lang.Integer getNeedCollectShop() {
		return get("need_collect_shop");
	}

	public M setQiandaoType(java.lang.Integer qiandaoType) {
		set("qiandao_type", qiandaoType);
		return (M)this;
	}

	public java.lang.Integer getQiandaoType() {
		return get("qiandao_type");
	}

	public M setAsSignPrize(java.lang.Integer asSignPrize) {
		set("as_sign_prize", asSignPrize);
		return (M)this;
	}

	public java.lang.Integer getAsSignPrize() {
		return get("as_sign_prize");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
