package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQiandaoConfig<M extends BaseQiandaoConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setQiandaoId(java.lang.Long qiandaoId) {
		set("qiandao_id", qiandaoId);
	}

	public java.lang.Long getQiandaoId() {
		return get("qiandao_id");
	}

	public void setSignType(java.lang.Integer signType) {
		set("sign_type", signType);
	}

	public java.lang.Integer getSignType() {
		return get("sign_type");
	}

	public void setSignDay(java.lang.String signDay) {
		set("sign_day", signDay);
	}

	public java.lang.String getSignDay() {
		return get("sign_day");
	}

	public void setPrizeId(java.lang.Long prizeId) {
		set("prize_id", prizeId);
	}

	public java.lang.Long getPrizeId() {
		return get("prize_id");
	}

	public void setPrizeName(java.lang.String prizeName) {
		set("prize_name", prizeName);
	}

	public java.lang.String getPrizeName() {
		return get("prize_name");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
