package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setSn(java.lang.String sn) {
		set("sn", sn);
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPrice(java.lang.String price) {
		set("price", price);
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public void setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
	}

	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public void setDeliveryWeight(java.math.BigDecimal deliveryWeight) {
		set("delivery_weight", deliveryWeight);
	}

	public java.math.BigDecimal getDeliveryWeight() {
		return get("delivery_weight");
	}

	public void setIsMarketable(java.lang.Boolean isMarketable) {
		set("is_marketable", isMarketable);
	}

	public java.lang.Boolean getIsMarketable() {
		return get("is_marketable");
	}

	public void setIsUnifiedSpec(java.lang.Boolean isUnifiedSpec) {
		set("is_unified_spec", isUnifiedSpec);
	}

	public java.lang.Boolean getIsUnifiedSpec() {
		return get("is_unified_spec");
	}

	public void setIsList(java.lang.Boolean isList) {
		set("is_list", isList);
	}

	public java.lang.Boolean getIsList() {
		return get("is_list");
	}

	public void setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public void setSales(java.lang.Long sales) {
		set("sales", sales);
	}

	public java.lang.Long getSales() {
		return get("sales");
	}

	public void setProductCategoryId(java.lang.Long productCategoryId) {
		set("product_category_id", productCategoryId);
	}

	public java.lang.Long getProductCategoryId() {
		return get("product_category_id");
	}

	public void setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
	}

	public java.lang.Integer getDeliveryType() {
		return get("delivery_type");
	}

	public void setDeliveryFees(java.math.BigDecimal deliveryFees) {
		set("delivery_fees", deliveryFees);
	}

	public java.math.BigDecimal getDeliveryFees() {
		return get("delivery_fees");
	}

	public void setDeliveryTemplateId(java.lang.Long deliveryTemplateId) {
		set("delivery_template_id", deliveryTemplateId);
	}

	public java.lang.Long getDeliveryTemplateId() {
		return get("delivery_template_id");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
