package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQiandaoRecord<M extends BaseQiandaoRecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setQiandaoId(java.lang.Long qiandaoId) {
		set("qiandao_id", qiandaoId);
	}

	public java.lang.Long getQiandaoId() {
		return get("qiandao_id");
	}

	public void setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public void setQiandaoTime(java.util.Date qiandaoTime) {
		set("qiandao_time", qiandaoTime);
	}

	public java.util.Date getQiandaoTime() {
		return get("qiandao_time");
	}

	public void setQiandaoMonth(java.lang.String qiandaoMonth) {
		set("qiandao_month", qiandaoMonth);
	}

	public java.lang.String getQiandaoMonth() {
		return get("qiandao_month");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
