package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuyerReceiver<M extends BaseBuyerReceiver<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public M setReceiverName(java.lang.String receiverName) {
		set("receiver_name", receiverName);
		return (M)this;
	}

	public java.lang.String getReceiverName() {
		return get("receiver_name");
	}

	public M setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
		return (M)this;
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public M setAreaTreePath(java.lang.String areaTreePath) {
		set("area_tree_path", areaTreePath);
		return (M)this;
	}

	public java.lang.String getAreaTreePath() {
		return get("area_tree_path");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setDistrict(java.lang.String district) {
		set("district", district);
		return (M)this;
	}

	public java.lang.String getDistrict() {
		return get("district");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public M setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
		return (M)this;
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public M setIsDefault(java.lang.Boolean isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}

	public java.lang.Boolean getIsDefault() {
		return get("is_default");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

}
