package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public M setOrderType(java.lang.Integer orderType) {
		set("order_type", orderType);
		return (M)this;
	}

	public java.lang.Integer getOrderType() {
		return get("order_type");
	}

	public M setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
		return (M)this;
	}

	public java.lang.String getOrderSn() {
		return get("order_sn");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}

	public java.lang.Integer getOrderStatus() {
		return get("order_status");
	}

	public M setPaymentStatus(java.lang.Integer paymentStatus) {
		set("payment_status", paymentStatus);
		return (M)this;
	}

	public java.lang.Integer getPaymentStatus() {
		return get("payment_status");
	}

	public M setShippingStatus(java.lang.Integer shippingStatus) {
		set("shipping_status", shippingStatus);
		return (M)this;
	}

	public java.lang.Integer getShippingStatus() {
		return get("shipping_status");
	}

	public M setGroupStatus(java.lang.Integer groupStatus) {
		set("group_status", groupStatus);
		return (M)this;
	}

	public java.lang.Integer getGroupStatus() {
		return get("group_status");
	}

	public M setReceiverId(java.lang.Long receiverId) {
		set("receiver_id", receiverId);
		return (M)this;
	}

	public java.lang.Long getReceiverId() {
		return get("receiver_id");
	}

	public M setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
		return (M)this;
	}

	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public M setPostFee(java.math.BigDecimal postFee) {
		set("post_fee", postFee);
		return (M)this;
	}

	public java.math.BigDecimal getPostFee() {
		return get("post_fee");
	}

	public M setPayFee(java.math.BigDecimal payFee) {
		set("pay_fee", payFee);
		return (M)this;
	}

	public java.math.BigDecimal getPayFee() {
		return get("pay_fee");
	}

	public M setPoint(java.lang.Long point) {
		set("point", point);
		return (M)this;
	}

	public java.lang.Long getPoint() {
		return get("point");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public M setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
		return (M)this;
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public M setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
		return (M)this;
	}

	public java.lang.String getTransactionId() {
		return get("transaction_id");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

}
