package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseModuleFun<M extends BaseModuleFun<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setModuleId(java.lang.Long moduleId) {
		set("module_id", moduleId);
		return (M)this;
	}

	public java.lang.Long getModuleId() {
		return get("module_id");
	}

	public M setModuleFunId(java.lang.Long moduleFunId) {
		set("module_fun_id", moduleFunId);
		return (M)this;
	}

	public java.lang.Long getModuleFunId() {
		return get("module_fun_id");
	}

	public M setFunName(java.lang.String funName) {
		set("fun_name", funName);
		return (M)this;
	}

	public java.lang.String getFunName() {
		return get("fun_name");
	}

	public M setFunUrl(java.lang.String funUrl) {
		set("fun_url", funUrl);
		return (M)this;
	}

	public java.lang.String getFunUrl() {
		return get("fun_url");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
