package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrize<M extends BasePrize<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setPrizeTypeId(java.lang.Long prizeTypeId) {
		set("prize_type_id", prizeTypeId);
	}

	public java.lang.Long getPrizeTypeId() {
		return get("prize_type_id");
	}

	public void setPrizeName(java.lang.String prizeName) {
		set("prize_name", prizeName);
	}

	public java.lang.String getPrizeName() {
		return get("prize_name");
	}

	public void setPrizeImg(java.lang.String prizeImg) {
		set("prize_img", prizeImg);
	}

	public java.lang.String getPrizeImg() {
		return get("prize_img");
	}

	public void setPrizePrice(java.lang.String prizePrice) {
		set("prize_price", prizePrice);
	}

	public java.lang.String getPrizePrice() {
		return get("prize_price");
	}

	public void setPrizeMemo(java.lang.String prizeMemo) {
		set("prize_memo", prizeMemo);
	}

	public java.lang.String getPrizeMemo() {
		return get("prize_memo");
	}

	public void setPrizeSingleCash(java.lang.Integer prizeSingleCash) {
		set("prize_single_cash", prizeSingleCash);
	}

	public java.lang.Integer getPrizeSingleCash() {
		return get("prize_single_cash");
	}

	public void setPublishCount(java.lang.Integer publishCount) {
		set("publish_count", publishCount);
	}

	public java.lang.Integer getPublishCount() {
		return get("publish_count");
	}

	public void setHadOutCount(java.lang.Integer hadOutCount) {
		set("had_out_count", hadOutCount);
	}

	public java.lang.Integer getHadOutCount() {
		return get("had_out_count");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setOutId(java.lang.String outId) {
		set("out_id", outId);
	}

	public java.lang.String getOutId() {
		return get("out_id");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
