package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}

	public java.lang.String getSn() {
		return get("sn");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setPrice(java.lang.String price) {
		set("price", price);
		return (M)this;
	}

	public java.lang.String getPrice() {
		return get("price");
	}

	public M setMarketPrice(java.math.BigDecimal marketPrice) {
		set("market_price", marketPrice);
		return (M)this;
	}

	public java.math.BigDecimal getMarketPrice() {
		return get("market_price");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public M setDeliveryWeight(java.math.BigDecimal deliveryWeight) {
		set("delivery_weight", deliveryWeight);
		return (M)this;
	}

	public java.math.BigDecimal getDeliveryWeight() {
		return get("delivery_weight");
	}

	public M setIsMarketable(java.lang.Boolean isMarketable) {
		set("is_marketable", isMarketable);
		return (M)this;
	}

	public java.lang.Boolean getIsMarketable() {
		return get("is_marketable");
	}

	public M setIsUnifiedSpec(java.lang.Boolean isUnifiedSpec) {
		set("is_unified_spec", isUnifiedSpec);
		return (M)this;
	}

	public java.lang.Boolean getIsUnifiedSpec() {
		return get("is_unified_spec");
	}

	public M setIsList(java.lang.Boolean isList) {
		set("is_list", isList);
		return (M)this;
	}

	public java.lang.Boolean getIsList() {
		return get("is_list");
	}

	public M setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
		return (M)this;
	}

	public java.lang.String getIntroduction() {
		return get("introduction");
	}

	public M setSales(java.lang.Long sales) {
		set("sales", sales);
		return (M)this;
	}

	public java.lang.Long getSales() {
		return get("sales");
	}

	public M setProductCategoryId(java.lang.Long productCategoryId) {
		set("product_category_id", productCategoryId);
		return (M)this;
	}

	public java.lang.Long getProductCategoryId() {
		return get("product_category_id");
	}

	public M setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
		return (M)this;
	}

	public java.lang.Integer getDeliveryType() {
		return get("delivery_type");
	}

	public M setDeliveryFees(java.math.BigDecimal deliveryFees) {
		set("delivery_fees", deliveryFees);
		return (M)this;
	}

	public java.math.BigDecimal getDeliveryFees() {
		return get("delivery_fees");
	}

	public M setDeliveryTemplateId(java.lang.Long deliveryTemplateId) {
		set("delivery_template_id", deliveryTemplateId);
		return (M)this;
	}

	public java.lang.Long getDeliveryTemplateId() {
		return get("delivery_template_id");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
