package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellerUser<M extends BaseSellerUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setNick(java.lang.String nick) {
		set("nick", nick);
		return (M)this;
	}

	public java.lang.String getNick() {
		return get("nick");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setUserLevel(java.lang.Integer userLevel) {
		set("user_level", userLevel);
		return (M)this;
	}

	public java.lang.Integer getUserLevel() {
		return get("user_level");
	}

	public M setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
		return (M)this;
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
		return (M)this;
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public M setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
		return (M)this;
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public M setVersionNo(java.lang.Integer versionNo) {
		set("version_no", versionNo);
		return (M)this;
	}

	public java.lang.Integer getVersionNo() {
		return get("version_no");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
		return (M)this;
	}

	public java.lang.String getLoginIp() {
		return get("login_ip");
	}

	public M setAdmiLoginFailureCount(java.lang.Integer admiLoginFailureCount) {
		set("admi_login_failure_count", admiLoginFailureCount);
		return (M)this;
	}

	public java.lang.Integer getAdmiLoginFailureCount() {
		return get("admi_login_failure_count");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
