package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQiandaoRecord<M extends BaseQiandaoRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setQiandaoId(java.lang.Long qiandaoId) {
		set("qiandao_id", qiandaoId);
		return (M)this;
	}

	public java.lang.Long getQiandaoId() {
		return get("qiandao_id");
	}

	public M setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
		return (M)this;
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public M setQiandaoTime(java.util.Date qiandaoTime) {
		set("qiandao_time", qiandaoTime);
		return (M)this;
	}

	public java.util.Date getQiandaoTime() {
		return get("qiandao_time");
	}

	public M setQiandaoMonth(java.lang.String qiandaoMonth) {
		set("qiandao_month", qiandaoMonth);
		return (M)this;
	}

	public java.lang.String getQiandaoMonth() {
		return get("qiandao_month");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
