package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFullCutSet<M extends BaseFullCutSet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setFullCutId(java.lang.Long fullCutId) {
		set("full_cut_id", fullCutId);
	}

	public java.lang.Long getFullCutId() {
		return get("full_cut_id");
	}

	public void setMeet(java.math.BigDecimal meet) {
		set("meet", meet);
	}

	public java.math.BigDecimal getMeet() {
		return get("meet");
	}

	public void setCashRequired(java.lang.Integer cashRequired) {
		set("cash_required", cashRequired);
	}

	public java.lang.Integer getCashRequired() {
		return get("cash_required");
	}

	public void setCash(java.math.BigDecimal cash) {
		set("cash", cash);
	}

	public java.math.BigDecimal getCash() {
		return get("cash");
	}

	public void setPostage(java.lang.Integer postage) {
		set("postage", postage);
	}

	public java.lang.Integer getPostage() {
		return get("postage");
	}

	public void setActive(java.lang.Boolean active) {
		set("active", active);
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
