package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQiandaoUser<M extends BaseQiandaoUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setQiandaoId(java.lang.Long qiandaoId) {
		set("qiandao_id", qiandaoId);
	}

	public java.lang.Long getQiandaoId() {
		return get("qiandao_id");
	}

	public void setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public void setQiandaoCount(java.lang.Integer qiandaoCount) {
		set("qiandao_count", qiandaoCount);
	}

	public java.lang.Integer getQiandaoCount() {
		return get("qiandao_count");
	}

	public void setCQiandaoCount(java.lang.Integer cQiandaoCount) {
		set("c_qiandao_count", cQiandaoCount);
	}

	public java.lang.Integer getCQiandaoCount() {
		return get("c_qiandao_count");
	}

	public void setSignDate(java.util.Date signDate) {
		set("sign_date", signDate);
	}

	public java.util.Date getSignDate() {
		return get("sign_date");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
