package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLotteryAward<M extends BaseLotteryAward<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setLotteryId(java.lang.Long lotteryId) {
		set("lottery_id", lotteryId);
	}

	public java.lang.Long getLotteryId() {
		return get("lottery_id");
	}

	public void setPrizeId(java.lang.Long prizeId) {
		set("prize_id", prizeId);
	}

	public java.lang.Long getPrizeId() {
		return get("prize_id");
	}

	public void setAwardPos(java.lang.Integer awardPos) {
		set("award_pos", awardPos);
	}

	public java.lang.Integer getAwardPos() {
		return get("award_pos");
	}

	public void setAwardName(java.lang.String awardName) {
		set("award_name", awardName);
	}

	public java.lang.String getAwardName() {
		return get("award_name");
	}

	public void setAwardCount(java.lang.Integer awardCount) {
		set("award_count", awardCount);
	}

	public java.lang.Integer getAwardCount() {
		return get("award_count");
	}

	public void setAwardRate(java.lang.Double awardRate) {
		set("award_rate", awardRate);
	}

	public java.lang.Double getAwardRate() {
		return get("award_rate");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
