package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommissionRate<M extends BaseCommissionRate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setSelfUpRate(java.math.BigDecimal selfUpRate) {
		set("self_up_rate", selfUpRate);
	}

	public java.math.BigDecimal getSelfUpRate() {
		return get("self_up_rate");
	}

	public void setSecondUpRate(java.math.BigDecimal secondUpRate) {
		set("second_up_rate", secondUpRate);
	}

	public java.math.BigDecimal getSecondUpRate() {
		return get("second_up_rate");
	}

	public void setThirdUpRate(java.math.BigDecimal thirdUpRate) {
		set("third_up_rate", thirdUpRate);
	}

	public java.math.BigDecimal getThirdUpRate() {
		return get("third_up_rate");
	}

	public void setSelfBuyRate(java.lang.Boolean selfBuyRate) {
		set("self_buy_rate", selfBuyRate);
	}

	public java.lang.Boolean getSelfBuyRate() {
		return get("self_buy_rate");
	}

	public void setActive(java.lang.Boolean active) {
		set("active", active);
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
