package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLotteryAward<M extends BaseLotteryAward<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setLotteryId(java.lang.Long lotteryId) {
		set("lottery_id", lotteryId);
		return (M)this;
	}

	public java.lang.Long getLotteryId() {
		return get("lottery_id");
	}

	public M setPrizeId(java.lang.Long prizeId) {
		set("prize_id", prizeId);
		return (M)this;
	}

	public java.lang.Long getPrizeId() {
		return get("prize_id");
	}

	public M setAwardPos(java.lang.Integer awardPos) {
		set("award_pos", awardPos);
		return (M)this;
	}

	public java.lang.Integer getAwardPos() {
		return get("award_pos");
	}

	public M setAwardName(java.lang.String awardName) {
		set("award_name", awardName);
		return (M)this;
	}

	public java.lang.String getAwardName() {
		return get("award_name");
	}

	public M setAwardCount(java.lang.Integer awardCount) {
		set("award_count", awardCount);
		return (M)this;
	}

	public java.lang.Integer getAwardCount() {
		return get("award_count");
	}

	public M setAwardRate(java.lang.Double awardRate) {
		set("award_rate", awardRate);
		return (M)this;
	}

	public java.lang.Double getAwardRate() {
		return get("award_rate");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
