package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQiandao<M extends BaseQiandao<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setQiandaoName(java.lang.String qiandaoName) {
		set("qiandao_name", qiandaoName);
	}

	public java.lang.String getQiandaoName() {
		return get("qiandao_name");
	}

	public void setStartDate(java.util.Date startDate) {
		set("start_date", startDate);
	}

	public java.util.Date getStartDate() {
		return get("start_date");
	}

	public void setEndDate(java.util.Date endDate) {
		set("end_date", endDate);
	}

	public java.util.Date getEndDate() {
		return get("end_date");
	}

	public void setActivityType(java.lang.Integer activityType) {
		set("activity_type", activityType);
	}

	public java.lang.Integer getActivityType() {
		return get("activity_type");
	}

	public void setQiandaoMemo(java.lang.String qiandaoMemo) {
		set("qiandao_memo", qiandaoMemo);
	}

	public java.lang.String getQiandaoMemo() {
		return get("qiandao_memo");
	}

	public void setWirlessUrl(java.lang.String wirlessUrl) {
		set("wirless_url", wirlessUrl);
	}

	public java.lang.String getWirlessUrl() {
		return get("wirless_url");
	}

	public void setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
	}

	public java.lang.String getQrCode() {
		return get("qr_code");
	}

	public void setBackImg(java.lang.String backImg) {
		set("back_img", backImg);
	}

	public java.lang.String getBackImg() {
		return get("back_img");
	}

	public void setNeedCollectShop(java.lang.Integer needCollectShop) {
		set("need_collect_shop", needCollectShop);
	}

	public java.lang.Integer getNeedCollectShop() {
		return get("need_collect_shop");
	}

	public void setQiandaoType(java.lang.Integer qiandaoType) {
		set("qiandao_type", qiandaoType);
	}

	public java.lang.Integer getQiandaoType() {
		return get("qiandao_type");
	}

	public void setAsSignPrize(java.lang.Integer asSignPrize) {
		set("as_sign_prize", asSignPrize);
	}

	public java.lang.Integer getAsSignPrize() {
		return get("as_sign_prize");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
