package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvoiceTemplate<M extends BaseInvoiceTemplate<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setInvTplcontent(java.lang.String invTplcontent) {
		set("inv_tplcontent", invTplcontent);
		return (M)this;
	}

	public java.lang.String getInvTplcontent() {
		return get("inv_tplcontent");
	}

	public M setInvDesignhtml(java.lang.String invDesignhtml) {
		set("inv_designhtml", invDesignhtml);
		return (M)this;
	}

	public java.lang.String getInvDesignhtml() {
		return get("inv_designhtml");
	}

	public M setInvTabelhtml(java.lang.String invTabelhtml) {
		set("inv_tabelhtml", invTabelhtml);
		return (M)this;
	}

	public java.lang.String getInvTabelhtml() {
		return get("inv_tabelhtml");
	}

	public M setInvImgDesignhtml(java.lang.String invImgDesignhtml) {
		set("inv_img_designhtml", invImgDesignhtml);
		return (M)this;
	}

	public java.lang.String getInvImgDesignhtml() {
		return get("inv_img_designhtml");
	}

	public M setPagewidth(java.lang.Integer pagewidth) {
		set("pagewidth", pagewidth);
		return (M)this;
	}

	public java.lang.Integer getPagewidth() {
		return get("pagewidth");
	}

	public M setPageheight(java.lang.Integer pageheight) {
		set("pageheight", pageheight);
		return (M)this;
	}

	public java.lang.Integer getPageheight() {
		return get("pageheight");
	}

	public M setOffsetx(java.lang.Integer offsetx) {
		set("offsetx", offsetx);
		return (M)this;
	}

	public java.lang.Integer getOffsetx() {
		return get("offsetx");
	}

	public M setOffsety(java.lang.Integer offsety) {
		set("offsety", offsety);
		return (M)this;
	}

	public java.lang.Integer getOffsety() {
		return get("offsety");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
