package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInvoiceTemplate<M extends BaseInvoiceTemplate<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setInvTplcontent(java.lang.String invTplcontent) {
		set("inv_tplcontent", invTplcontent);
	}

	public java.lang.String getInvTplcontent() {
		return get("inv_tplcontent");
	}

	public void setInvDesignhtml(java.lang.String invDesignhtml) {
		set("inv_designhtml", invDesignhtml);
	}

	public java.lang.String getInvDesignhtml() {
		return get("inv_designhtml");
	}

	public void setInvTabelhtml(java.lang.String invTabelhtml) {
		set("inv_tabelhtml", invTabelhtml);
	}

	public java.lang.String getInvTabelhtml() {
		return get("inv_tabelhtml");
	}

	public void setInvImgDesignhtml(java.lang.String invImgDesignhtml) {
		set("inv_img_designhtml", invImgDesignhtml);
	}

	public java.lang.String getInvImgDesignhtml() {
		return get("inv_img_designhtml");
	}

	public void setPagewidth(java.lang.Integer pagewidth) {
		set("pagewidth", pagewidth);
	}

	public java.lang.Integer getPagewidth() {
		return get("pagewidth");
	}

	public void setPageheight(java.lang.Integer pageheight) {
		set("pageheight", pageheight);
	}

	public java.lang.Integer getPageheight() {
		return get("pageheight");
	}

	public void setOffsetx(java.lang.Integer offsetx) {
		set("offsetx", offsetx);
	}

	public java.lang.Integer getOffsetx() {
		return get("offsetx");
	}

	public void setOffsety(java.lang.Integer offsety) {
		set("offsety", offsety);
	}

	public java.lang.Integer getOffsety() {
		return get("offsety");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
