package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setBuyerId(java.lang.Long buyerId) {
		set("buyer_id", buyerId);
	}

	public java.lang.Long getBuyerId() {
		return get("buyer_id");
	}

	public void setOrderSn(java.lang.String orderSn) {
		set("order_sn", orderSn);
	}

	public java.lang.String getOrderSn() {
		return get("order_sn");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}

	public java.lang.Integer getOrderStatus() {
		return get("order_status");
	}

	public void setPaymentStatus(java.lang.Integer paymentStatus) {
		set("payment_status", paymentStatus);
	}

	public java.lang.Integer getPaymentStatus() {
		return get("payment_status");
	}

	public void setShippingStatus(java.lang.Integer shippingStatus) {
		set("shipping_status", shippingStatus);
	}

	public java.lang.Integer getShippingStatus() {
		return get("shipping_status");
	}

	public void setReceiverId(java.lang.Long receiverId) {
		set("receiver_id", receiverId);
	}

	public java.lang.Long getReceiverId() {
		return get("receiver_id");
	}

	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
	}

	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public void setPostFee(java.math.BigDecimal postFee) {
		set("post_fee", postFee);
	}

	public java.math.BigDecimal getPostFee() {
		return get("post_fee");
	}

	public void setPayFee(java.math.BigDecimal payFee) {
		set("pay_fee", payFee);
	}

	public java.math.BigDecimal getPayFee() {
		return get("pay_fee");
	}

	public void setPoint(java.lang.Long point) {
		set("point", point);
	}

	public java.lang.Long getPoint() {
		return get("point");
	}

	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public void setTradeNo(java.lang.String tradeNo) {
		set("trade_no", tradeNo);
	}

	public java.lang.String getTradeNo() {
		return get("trade_no");
	}

	public void setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
	}

	public java.lang.String getTransactionId() {
		return get("transaction_id");
	}

	public void setInvoiceTitle(java.lang.String invoiceTitle) {
		set("invoice_title", invoiceTitle);
	}

	public java.lang.String getInvoiceTitle() {
		return get("invoice_title");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public void setActive(java.lang.Boolean active) {
		set("active", active);
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

}
