package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseModule<M extends BaseModule<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setModuleName(java.lang.String moduleName) {
		set("module_name", moduleName);
	}

	public java.lang.String getModuleName() {
		return get("module_name");
	}

	public void setClassName(java.lang.String className) {
		set("class_name", className);
	}

	public java.lang.String getClassName() {
		return get("class_name");
	}

	public void setTableName(java.lang.String tableName) {
		set("table_name", tableName);
	}

	public java.lang.String getTableName() {
		return get("table_name");
	}

	public void setParamName(java.lang.String paramName) {
		set("param_name", paramName);
	}

	public java.lang.String getParamName() {
		return get("param_name");
	}

	public void setModuleUrl(java.lang.String moduleUrl) {
		set("module_url", moduleUrl);
	}

	public java.lang.String getModuleUrl() {
		return get("module_url");
	}

	public void setModuleCode(java.lang.String moduleCode) {
		set("module_code", moduleCode);
	}

	public java.lang.String getModuleCode() {
		return get("module_code");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
