package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBuyerRecharge<M extends BaseBuyerRecharge<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setBuyerUserId(java.lang.Long buyerUserId) {
		set("buyer_user_id", buyerUserId);
	}

	public java.lang.Long getBuyerUserId() {
		return get("buyer_user_id");
	}

	public void setRecharge(java.lang.String recharge) {
		set("recharge", recharge);
	}

	public java.lang.String getRecharge() {
		return get("recharge");
	}

	public void setOutTradeId(java.lang.String outTradeId) {
		set("out_trade_id", outTradeId);
	}

	public java.lang.String getOutTradeId() {
		return get("out_trade_id");
	}

	public void setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
	}

	public java.lang.String getTransactionId() {
		return get("transaction_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
