package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDeliverySet<M extends BaseDeliverySet<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setTemplateId(java.lang.Long templateId) {
		set("template_id", templateId);
		return (M)this;
	}

	public java.lang.Long getTemplateId() {
		return get("template_id");
	}

	public M setValuationType(java.lang.Long valuationType) {
		set("valuation_type", valuationType);
		return (M)this;
	}

	public java.lang.Long getValuationType() {
		return get("valuation_type");
	}

	public M setAreaId(java.lang.String areaId) {
		set("area_id", areaId);
		return (M)this;
	}

	public java.lang.String getAreaId() {
		return get("area_id");
	}

	public M setStartStandards(java.lang.Integer startStandards) {
		set("start_standards", startStandards);
		return (M)this;
	}

	public java.lang.Integer getStartStandards() {
		return get("start_standards");
	}

	public M setStartFees(java.math.BigDecimal startFees) {
		set("start_fees", startFees);
		return (M)this;
	}

	public java.math.BigDecimal getStartFees() {
		return get("start_fees");
	}

	public M setAddStandards(java.lang.Integer addStandards) {
		set("add_standards", addStandards);
		return (M)this;
	}

	public java.lang.Integer getAddStandards() {
		return get("add_standards");
	}

	public M setAddFees(java.math.BigDecimal addFees) {
		set("add_fees", addFees);
		return (M)this;
	}

	public java.math.BigDecimal getAddFees() {
		return get("add_fees");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
