package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCashback<M extends BaseCashback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
	}

	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
	}

	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public void setCashbackMethod(java.lang.Integer cashbackMethod) {
		set("cashback_method", cashbackMethod);
	}

	public java.lang.Integer getCashbackMethod() {
		return get("cashback_method");
	}

	public void setCashbackStart(java.math.BigDecimal cashbackStart) {
		set("cashback_start", cashbackStart);
	}

	public java.math.BigDecimal getCashbackStart() {
		return get("cashback_start");
	}

	public void setCashbackEnd(java.math.BigDecimal cashbackEnd) {
		set("cashback_end", cashbackEnd);
	}

	public java.math.BigDecimal getCashbackEnd() {
		return get("cashback_end");
	}

	public void setCashbackLimit(java.lang.Integer cashbackLimit) {
		set("cashback_limit", cashbackLimit);
	}

	public java.lang.Integer getCashbackLimit() {
		return get("cashback_limit");
	}

	public void setProductIds(java.lang.String productIds) {
		set("product_ids", productIds);
	}

	public java.lang.String getProductIds() {
		return get("product_ids");
	}

	public void setActive(java.lang.Boolean active) {
		set("active", active);
	}

	public java.lang.Boolean getActive() {
		return get("active");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
