package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQiandaoConfig<M extends BaseQiandaoConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setQiandaoId(java.lang.Long qiandaoId) {
		set("qiandao_id", qiandaoId);
		return (M)this;
	}

	public java.lang.Long getQiandaoId() {
		return get("qiandao_id");
	}

	public M setSignType(java.lang.Integer signType) {
		set("sign_type", signType);
		return (M)this;
	}

	public java.lang.Integer getSignType() {
		return get("sign_type");
	}

	public M setSignDay(java.lang.String signDay) {
		set("sign_day", signDay);
		return (M)this;
	}

	public java.lang.String getSignDay() {
		return get("sign_day");
	}

	public M setPrizeId(java.lang.Long prizeId) {
		set("prize_id", prizeId);
		return (M)this;
	}

	public java.lang.Long getPrizeId() {
		return get("prize_id");
	}

	public M setPrizeName(java.lang.String prizeName) {
		set("prize_name", prizeName);
		return (M)this;
	}

	public java.lang.String getPrizeName() {
		return get("prize_name");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
