package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuyerUser<M extends BaseBuyerUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setMemberRankId(java.lang.Long memberRankId) {
		set("member_rank_id", memberRankId);
		return (M)this;
	}

	public java.lang.Long getMemberRankId() {
		return get("member_rank_id");
	}

	public M setUserOrigin(java.lang.Integer userOrigin) {
		set("user_origin", userOrigin);
		return (M)this;
	}

	public java.lang.Integer getUserOrigin() {
		return get("user_origin");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
		return (M)this;
	}

	public java.lang.String getHeadimgurl() {
		return get("headimgurl");
	}

	public M setOpenId(java.lang.String openId) {
		set("open_id", openId);
		return (M)this;
	}

	public java.lang.String getOpenId() {
		return get("open_id");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public M setLanguage(java.lang.String language) {
		set("language", language);
		return (M)this;
	}

	public java.lang.String getLanguage() {
		return get("language");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public M setSubscribe(java.lang.Integer subscribe) {
		set("subscribe", subscribe);
		return (M)this;
	}

	public java.lang.Integer getSubscribe() {
		return get("subscribe");
	}

	public M setSubscribeTime(java.util.Date subscribeTime) {
		set("subscribe_time", subscribeTime);
		return (M)this;
	}

	public java.util.Date getSubscribeTime() {
		return get("subscribe_time");
	}

	public M setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
		return (M)this;
	}

	public java.lang.Integer getGroupid() {
		return get("groupid");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setAccessIp(java.lang.String accessIp) {
		set("access_ip", accessIp);
		return (M)this;
	}

	public java.lang.String getAccessIp() {
		return get("access_ip");
	}

	public M setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
		return (M)this;
	}

	public java.lang.String getAccessToken() {
		return get("access_token");
	}

	public M setRefreshToken(java.lang.String refreshToken) {
		set("refresh_token", refreshToken);
		return (M)this;
	}

	public java.lang.String getRefreshToken() {
		return get("refresh_token");
	}

	public M setTokenExpiresIn(java.lang.String tokenExpiresIn) {
		set("token_expires_in", tokenExpiresIn);
		return (M)this;
	}

	public java.lang.String getTokenExpiresIn() {
		return get("token_expires_in");
	}

	public M setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
		return (M)this;
	}

	public java.util.Date getLastLoginTime() {
		return get("last_login_time");
	}

	public M setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
		return (M)this;
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
