package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDeliverySet<M extends BaseDeliverySet<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setTemplateId(java.lang.Long templateId) {
		set("template_id", templateId);
	}

	public java.lang.Long getTemplateId() {
		return get("template_id");
	}

	public void setValuationType(java.lang.Long valuationType) {
		set("valuation_type", valuationType);
	}

	public java.lang.Long getValuationType() {
		return get("valuation_type");
	}

	public void setAreaId(java.lang.String areaId) {
		set("area_id", areaId);
	}

	public java.lang.String getAreaId() {
		return get("area_id");
	}

	public void setStartStandards(java.lang.Integer startStandards) {
		set("start_standards", startStandards);
	}

	public java.lang.Integer getStartStandards() {
		return get("start_standards");
	}

	public void setStartFees(java.math.BigDecimal startFees) {
		set("start_fees", startFees);
	}

	public java.math.BigDecimal getStartFees() {
		return get("start_fees");
	}

	public void setAddStandards(java.lang.Integer addStandards) {
		set("add_standards", addStandards);
	}

	public java.lang.Integer getAddStandards() {
		return get("add_standards");
	}

	public void setAddFees(java.math.BigDecimal addFees) {
		set("add_fees", addFees);
	}

	public java.math.BigDecimal getAddFees() {
		return get("add_fees");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public void setActive(java.lang.Integer active) {
		set("active", active);
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
