package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePurchase<M extends BasePurchase<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public M setExpiresIn(java.lang.Integer expiresIn) {
		set("expires_in", expiresIn);
		return (M)this;
	}

	public java.lang.Integer getExpiresIn() {
		return get("expires_in");
	}

	public M setPayFee(java.lang.Double payFee) {
		set("pay_fee", payFee);
		return (M)this;
	}

	public java.lang.Double getPayFee() {
		return get("pay_fee");
	}

	public M setIsDefault(java.lang.Integer isDefault) {
		set("is_default", isDefault);
		return (M)this;
	}

	public java.lang.Integer getIsDefault() {
		return get("is_default");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

}
