package com.dbumama.market.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSellerAddr<M extends BaseSellerAddr<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setSellerId(java.lang.Long sellerId) {
		set("seller_id", sellerId);
		return (M)this;
	}

	public java.lang.Long getSellerId() {
		return get("seller_id");
	}

	public M setAreaId(java.lang.Long areaId) {
		set("area_id", areaId);
		return (M)this;
	}

	public java.lang.Long getAreaId() {
		return get("area_id");
	}

	public M setContactName(java.lang.String contactName) {
		set("contact_name", contactName);
		return (M)this;
	}

	public java.lang.String getContactName() {
		return get("contact_name");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setAddr(java.lang.String addr) {
		set("addr", addr);
		return (M)this;
	}

	public java.lang.String getAddr() {
		return get("addr");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public M setSellerCompany(java.lang.String sellerCompany) {
		set("seller_company", sellerCompany);
		return (M)this;
	}

	public java.lang.String getSellerCompany() {
		return get("seller_company");
	}

	public M setZipCode(java.lang.String zipCode) {
		set("zip_code", zipCode);
		return (M)this;
	}

	public java.lang.String getZipCode() {
		return get("zip_code");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setUpdated(java.util.Date updated) {
		set("updated", updated);
		return (M)this;
	}

	public java.util.Date getUpdated() {
		return get("updated");
	}

	public M setActive(java.lang.Integer active) {
		set("active", active);
		return (M)this;
	}

	public java.lang.Integer getActive() {
		return get("active");
	}

}
